Algoritmo "enquantoFacaNumero1a10"
// O algoritimo só aceita número no intervalo de 1 a 10, se não for, aparecer a mensagem denovo
Var

numero : inteiro

Inicio

   escreval("Digite o numero: ")
   leia(numero)

               Enquanto (numero < 1) ou (numero > 10) Faca
                        Escreval("Digite o numero: ")
                        leia(numero)
               FimEnquanto

   escreval("Você digitou um número entre 1 e 10")

Fimalgoritmo