Algoritmo "while"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/12/2025
Var

letra : caractere

Inicio

enquanto letra <> "b" Faca
         escreval("Digite o caractere: ")
         leia(letra)

fimEnquanto
escreval("Você digitou o b")

Fimalgoritmo