Algoritmo "numeroDiferentede5"
//Enquanto numero for diferente de 5, rodar código, quando clicar 5, encerrar.
Var

numero, resultado : real

Inicio

escreval("Digite o numero: ")
leia(numero)

            Enquanto (numero <> 5) FACA
                       escreval("Digite o numero: ")
                       leia(numero)
                       resultado <- resultado + numero
            FimEnquanto
            
escreval("A soma dos numeros é de:", resultado)


Fimalgoritmo