Algoritmo "tabuada"
// o algoritimo irá gerar uma tabuada de acordo com o número digitado
Var

numero, contador, tabuada: inteiro

Inicio

      escreval("Digite o valor que você deseja saber a tabuada: ")
      leia(numero)
      
      Enquanto (contador < 10) FACA
               contador <- contador + 1
               tabuada <- numero * contador
               escreval("O valor de", numero, "vezes", contador, " é de", tabuada)
      FimEnquanto
Fimalgoritmo